### ISSUE TITLE
Applying special formatting to phone numbers

### ISSUE THREAD

**Issue by LarBearrr** [Propaganistas/Laravel-Phone#133]
Apologies if this is not the appropriate channel for my question...

Can I use this package to apply special formatting to my phone numbers? i.e. (555) 555-1212

Thanks for your support and feedback!

**Comment by Propaganistas** [comment]
You can use any of the definitions [here](https://github.com/giggsey/libphonenumber-for-php/blob/master/src/PhoneNumberFormat.php) to automatically format any number, however your desired format is unsupported. Probably due to the fact that your formatting rules cannot be applied globally to any number. _Libphonenumber_ does not include any country-specific formatting rules. You'll have to use regex for that...

**Comment by LarBearrr** [comment]
Thanks for the clarification! Appreciate the prompt feedback.
