### ISSUE TITLE
Validation fail for a french phone number

### ISSUE THREAD

**Issue by simpledev** [Propaganistas/Laravel-Phone#147]
When I try to validate this phone number 0728553463 the validation fail.

Here's the validation rules for the phone field : 

`[
  'phone'=>'required|phone:FR',
]`

Tested here https://laravel-phone.herokuapp.com/ and the result is "Validation failed" with the error message "The field field contains an invalid number."

![validation_fail](https://user-images.githubusercontent.com/2912268/87954107-31635300-caac-11ea-993a-6ca4cc127faf.png)

Is it a bug or I'm doing something wrong?

**Comment by Propaganistas** [comment]
The number you're validating is invalid according to libphonenumber:

![Schermafbeelding 2020-07-24 om 17 13 37](https://user-images.githubusercontent.com/6680176/88406526-19077700-cdd1-11ea-9a33-4e8df0e55ec3.png)

**Comment by i-polaris** [comment]
@Propaganistas Actually 07 xx xx xx xx, is valid mobile phone, i didn't know why libphonenumber is invalid

is phone number for mobile only, and today if you get a new phone number you can only get 07 ...


btw this error causing some issue in my project, 

let me know if i'm wrong but for now you are doing all the check with libphonenumber ? so that mean if we wanted to fix we should fix it into libphonenumber ?

Best

**Comment by Propaganistas** [comment]
correct

**Comment by i-polaris** [comment]
Just to tell you i found the raison why this 0728.... is not working and why my test where not working too 

cause in french 07 numbers are only valid from 0730xxxxxx to 0789xxxxxx.
