### ISSUE TITLE
Method Illuminate\Support\Collection::phone does not exist.

### ISSUE THREAD

**Issue by eliomartinezb** [Propaganistas/Laravel-Phone#149]
I followed the instructions exactly as in the readme (it isn't that difficult)

I'm trying to simply validate if a phone number with the following code I have just started to test the framework.

        $request = collect(['phone' => '+593997526287']);

        $validation = Validator::make($request->all(), [
            'phone' => 'required|phone:AUTO',
        ]);

        if ($validation->fails()) {
            return response()->json([
                'status' => 'some fields are not valid.',
                'results' => $validation->errors(),
            ], 400);
        }

        return response()->json([
            'response' => $request->phone()
        ], 200);

And I get the following error:

Method Illuminate\Support\Collection::phone does not exist. in file .../vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php on line 103

**Comment by Propaganistas** [comment]
Your issue is unrelated to this package. You're abusing Laravel itself. You're fabricating a "fake request" by creating a `Collection` 
using `collect()`.

```
$request = collect(['phone' => '+593997526287']);

$validation = Validator::make($request->all(), [
    'phone' => 'required|phone:AUTO',
]);
```

The `Validator::make()` method either accepts a `Request` object or an array. Not a `Collection`. See the following:

* https://laravel.com/docs/7.x/validation#quick-writing-the-validation-logic
* https://laravel.com/docs/7.x/validation#manually-creating-validators
* https://laravel.com/docs/7.x/validation#validating-arrays

So all of the below are valid:

```
$input = ['phone' => '+593997526287'];

$validation = Validator::make($input, [
    'phone' => 'required|phone:AUTO',
]);
```

or

```
$request = request();

$validation = Validator::make($request->all(), [
    'phone' => 'required|phone:AUTO',
]);
```

or

```
public function some_controller_method(Request $request) {
    $validation = $request->validate([
        'phone' => 'required|phone:AUTO',
    ]);
}
```

**Comment by Propaganistas** [comment]
This issue is unrelated to the package.
You're abusing the Laravel framework and `Collections`. There's no such thing as a "phone" method on your fabricated collection (in the `$request` variable).

``` 
return response()->json([
        'response' => $request->phone()
    ], 200);
```
