### ISSUE TITLE
InvalidArgumentException : Missing country specification for phone attribute cast

### ISSUE THREAD

**Issue by ajmeireles** [Propaganistas/Laravel-Phone#224]
Hey, guys!

I updated my Laravel app to v10 and after that I am getting an error when trying to validate a phone number via test case using PestPHP. This test has existed since before the upgrade to Laravel v10.

1. The test case:
![image](https://user-images.githubusercontent.com/60591772/226196194-a72079aa-1696-4af0-8aeb-c2073941c474.png)

2. The validation that will be applied (Livewire Component):
![image](https://user-images.githubusercontent.com/60591772/226196222-e6555d7b-7282-4f7e-abd7-0af8080a4a84.png)

3. Model:
![image](https://user-images.githubusercontent.com/60591772/226196250-612f5b0d-2698-4c23-99e0-fbd7c3824815.png)

4. The error:
![image](https://user-images.githubusercontent.com/60591772/226196302-0b3fed82-0b2e-4041-8f71-b80d413a1a25.png)

Debugging the `RawPhoneNumberCast` class of the laravel-phone and I saw that in some cases the country is passed as empty:

![image](https://user-images.githubusercontent.com/60591772/226196589-d094303f-c890-4379-ba8a-9765ec048b12.png)
![image](https://user-images.githubusercontent.com/60591772/226196669-4b6a720b-30a5-4700-8af1-615eb520cbde.png)

I'm doing something wrong?

**Comment by Propaganistas** [comment]
Are you sure nothing else has changed?
The debug screenshots of `RawPhoneNumberCast` point to the second case of the validation test:

```php
['phone', '12345', 'min']
```

When running the following on a fresh Laravel instance, validation fails as expected:

```php
validator(['phone' => '12345'], ['phone' => 'phone:BR'])->passes() // false
```

So in fact value  `12345` should never have ended up in a model and hence never even invoke `RawPhoneNumberCast`...

I'm afraid the package works as designed and the root cause has to be found elsewhere... (Livewire? A controller? ...?)

**Comment by ajmeireles** [comment]
@Propaganistas ,

Here is the demonstration: https://www.loom.com/share/9485e579382a48f5aea9f05807c601ae

I think there is some bug with the code, or you think I'm doing something wrong according to the video?

**Comment by ajmeireles** [comment]
I was not able to understand the reason, but I found a possible fix:

The `getPossibleCountries` always returns as `BR` even the number is something like: 12345 - **that's the correct behavior.**
![image](https://user-images.githubusercontent.com/60591772/226510843-63fa6b40-2f6b-4acd-9412-c101e30c8b98.png)
![image](https://user-images.githubusercontent.com/60591772/226510926-6548ad43-34aa-450c-b4c4-055b8958720b.png)

The fix:
![image](https://user-images.githubusercontent.com/60591772/226511096-68b7f193-b0f9-4271-adb9-88da17abc948.png)

**Comment by Propaganistas** [comment]
Thanks for the investigation. It clearly points out that there's a breaking change I forgot to mention in the release notes.

I'm not tempted to "fix" this scenario though. When using `RawPhoneNumberCast` you should ensure that only valid phone numbers make it into the model. Otherwise the cast will never be able to return a usable phone object when accessing the attribute. In v4 the cast gracefully returned an invalid phone object and that's why your tests passed, but now in v5 that behavior is aligned with `E164PhoneNumberCast` and it'll only accept valid phone numbers in order to avoid unexpected stuff later down the line.

So I think the way forward is to check how it's possible that the invalid value ends up in the model, and then prevent that.
