### ISSUE TITLE
Documented formatE164 method does not return expected result

### ISSUE THREAD

**Issue by roarkmccolgan** [Propaganistas/Laravel-Phone#234]
Hi!

Trying the documented code for formatE164() method fails to return the number as expected:
```php
use Propaganistas\LaravelPhone\PhoneNumber;

$phone = new PhoneNumber('0712871097', 'ZA');
$phone = $phone->formatE164();
echo $phone; //Expect +27712871097

//Got:
//Propaganistas\LaravelPhone\Exceptions\NumberParseException  Number requires a country to be specified.
```

Please let me know if I'm missing something
As specified in the docs:

Thanks!

**Comment by Propaganistas** [comment]
Sorry, can't reproduce this. I added your case as a test:

https://github.com/Propaganistas/Laravel-Phone/blob/5ba16ee0091db35c5a704ff800ae218882336440/tests/PhoneNumberTest.php#L529-L536

...and the entire test suite turns [green](https://github.com/Propaganistas/Laravel-Phone/actions/runs/5824131020), and so this added test.

Are you sure the pasted code is what you have in your codebase? Errors mostly happen because of variables not having the value they ought to have.
