### ISSUE TITLE
Nullable rule doesn't work at request validation.

### ISSUE THREAD

**Issue by tanogalego** [Propaganistas/Laravel-Phone#249]
At laravel-phone version "^5.1". The 'nullable' rule is ignored:

```
public function rules(): array
    {
        return [
            'phone' => ['nullable', 'phone:INTERNATIONAL,US'],
        ];
}
```

The above code returns always an error when a `null` value is sent on the `$request->phone` field.

**Comment by Propaganistas** [comment]
I'm afraid something must be wrong on your end.
This scenario is tested and the demo application also exhibits the expected behavior:

<img width="1294" alt="Scherm­afbeelding 2024-04-05 om 21 50 26" src="https://github.com/Propaganistas/Laravel-Phone/assets/6680176/93b69a37-5ee5-43a3-b4d9-83269aaee440">
