### ISSUE TITLE
Detected Country field name configurable?

### ISSUE THREAD

**Issue by mikemand** [Propaganistas/Laravel-Phone#26]
Is it possible to configure the name of the Country field? Using `phone_country` as my field name does not make any sense (and does not fit in with my database design).

**Comment by Propaganistas** [comment]
Hello. At the moment this isn't possible. The country field has to be named similar as the phone field but with `_country` appended (e.g. `cellphone` and `cellphone_country`).

While I do not necessarily agree on using the same names for form fields and database columns by means of database design (moreover since validators are in fact not directly related to database design), I do see a use case for providing a custom country field name.

Currently I'm out of time to add this in short term so I'll be happy to accept a PR.

**Comment by mikemand** [comment]
Do you have any specific way you wish this to be implemented? My first thought would be to just add a config file that the Provider can publish.

**Comment by Propaganistas** [comment]
I'd like to see it implemented as a validator parameter so the customized behavior can optionally be applied on request.

**Comment by mikemand** [comment]
Ok, I'll send you a pull request as soon as I can - unless someone else beats me to it. Thanks!
