### ISSUE TITLE
Getting :value on custom messages

### ISSUE THREAD

**Issue by morfin** [Propaganistas/Laravel-Phone#45]
Could you add a replacer so :value becomes available from the custom message?

     $validator->addReplacer('phone', function ($message, $attribute, $rule, $parameters) use ($value) {
            return str_replace(':value', $value, $message);
        });

This allows:
"phone" => "The number :value is invalid.",

Thanks.

**Comment by Propaganistas** [comment]
Hi

Using the input value as a replacer is something Laravel doesn't support "officially". The correct way to add a custom replacer is by using `Validator::replacer()`. Unfortunately there's currently no way to reach the input data as the exposed variables consist of `$message, $attribute, $rule, $parameters`.

The code snippet you suggested is more of a hack since the replacer would get added each time the phone validator runs.

A suggestion would be to submit a PR to [laravel/framework](laravel/framework) to also expose the `$validator` to replacers. This way we can use `$validator->getValue()` in the replacer.

**Comment by morfin** [comment]
I ended up extending Illuminate/Validation/Validator.php.

Thanks.
