### ISSUE TITLE
Error Occur Undefined index: phone

### ISSUE THREAD

**Issue by taishjason** [Propaganistas/Laravel-Phone#49]
Hi, I am new to laravel. Currently using 5.4 version. After following the readme, I encounter

> ErrorException in RegisterController.php line 71: Undefined index: phone

Kindly help.

**Comment by taishjason** [comment]
I fix it, but there is a new issue. It didt not validate the phone number.

**Comment by Propaganistas** [comment]
Elaborating the context would greatly help. What you're trying to do, the
causing code,...

Op 13-feb.-2017 08:24 schreef "Jason Tai" <notifications@github.com>:

I fix it, but there is a new issue. It didt not validate the phone number.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Propaganistas/Laravel-Phone/issues/49#issuecomment-279311937>,
or mute the thread

**Comment by kiwina** [comment]
I think i know what he means i kind of have the same issue with an alternate phone number with i have sometimes on both fields and i get a NoValidCountryFoundException is there a way around it?
