### ISSUE TITLE
Error validating with mobile type "InvalidParameterException"

### ISSUE THREAD

**Issue by lyonlim** [Propaganistas/Laravel-Phone#60]
The following returns an error "InvalidParameterException" when you use a validation rule such as
`'phone' => 'phone:US,BE,mobile'`

It works if you remove the mobile instead:
`'phone' => 'phone:US,BE'`

Curiously, fixed_line works.

**Comment by Propaganistas** [comment]
Did you install the latest version? If so, please copy the exception's
stacktrace.

**Comment by lyonlim** [comment]
Thanks for the fast reply.
I'm using 3.0.2


`
(1/1) InvalidParameterExceptionInvalid phone validation parameters: "+6591235678".
--
in InvalidParameterException.php (line 17)
at InvalidParameterException::parameters(object(Collection))in Phone.php (line 124)
at Phone->extractParameters('mobile', array('SG', 'MY', 'mobile', '+6591235678'), array('_token' => 'KfUGk6KAHKuIQBeQerlWklmgaTW9WKB7ba2OeeH4', 'mobile' => '+6591235678'))in Phone.php (line 47)
at Phone->validate('mobile', '+6591235678', array('SG', 'MY', 'mobile'), object(Validator))
at call_user_func_array(array(object(Phone), 'validate'), array('mobile', '+6591235678', array('SG', 'MY', 'mobile'), object(Validator)))in Validator.php (line 1090)
at Validator->callClassBasedExtension('Propaganistas\\LaravelPhone\\Validation\\Phone@validate', array('mobile', '+6591235678', array('SG', 'MY', 'mobile'), object(Validator)))in Validator.php (line 1075)
at Validator->callExtension('phone', array('mobile', '+6591235678', array('SG', 'MY', 'mobile'), object(Validator)))in Validator.php (line 1107)
at Validator->__call('validatePhone', array('mobile', '+6591235678', array('SG', 'MY', 'mobile'), object(Validator)))in Validator.php (line 352)
at Validator->validateAttribute('mobile', 'Phone')in Validator.php (line 267)
at Validator->passes()in AttendanceController.php (line 40)
at AttendanceController->doRegister(object(Request), '1')
at call_user_func_array(array(object(AttendanceController), 'doRegister'), array(object(Request), 'id' => '1'))in Controller.php (line 55)
at Controller->callAction('doRegister', array(object(Request), 'id' => '1'))in ControllerDispatcher.php (line 44)
at ControllerDispatcher->dispatch(object(Route), object(AttendanceController), 'doRegister')in Route.php (line 203)
at Route->runController()in Route.php (line 160)
at Route->run()in Router.php (line 574)
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php (line 41)
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 65)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 576)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 535)
at Router->dispatchToRoute(object(Request))in Router.php (line 513)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php (line 27)
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 53)
`

**Comment by Propaganistas** [comment]
You're passing the phone number as a validator parameter. You shouldn't do
that.

**Comment by joebon** [comment]
@Propaganistas I have a very similar problem to this, which makes me suspect there is actually a bug present and not just mis-usage.
The following snippet results in basically the same stack trace as @lyonlim's:

```
        $validator = \Validator::make(
            ['mobile' => '+46731234567'],
            ['mobile' => 'phone:SE,mobile']
        );
        $validator->fails();
```
My (truncated) stack trace:

```
#0 [obfuscated path]/vendor/propaganistas/laravel-phone/src/Validation/Phone.php(124): Propaganistas\LaravelPhone\Exceptions\InvalidParameterException::parameters(Object(Illuminate\Support\Collection))
#1 [obfuscated path]/vendor/propaganistas/laravel-phone/src/Validation/Phone.php(47): Propaganistas\LaravelPhone\Validation\Phone->extractParameters('mobile', Array, Array)
#2 [internal function]: Propaganistas\LaravelPhone\Validation\Phone->validate('mobile', '+46731234567', Array, Object(App\Api\MyValidator))
#3 [obfuscated path]/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(2621): call_user_func_array(Array, Array)
#4 [obfuscated path]/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(2606): Illuminate\Validation\Validator->callClassBasedExtension('Propaganistas\\L...', Array)
#5 [obfuscated path]/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(2691): Illuminate\Validation\Validator->callExtension('phone', Array)
#6 [obfuscated path]/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(363): Illuminate\Validation\Validator->__call('validatePhone', Array)
#7 [obfuscated path]/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(315): Illuminate\Validation\Validator->validate('mobile', 'Phone')
#8 [obfuscated path]/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(336): Illuminate\Validation\Validator->passes()
...
```

However, changing the name of the field `mobile` to something else, let's say `foo`, makes it work as expected.

`Phone->validate('mobile', '+46731234567', Array, Object(App\Api\MyValidator))` is the revealing part, I would say.
https://github.com/Propaganistas/Laravel-Phone/blob/3.0.2/src/Validation/Phone.php#L47 calls `$this->extractParameters($attribute, $parameters, $data);`, where `$data` is just `['mobile' => '+46731234567']` (https://github.com/Propaganistas/Laravel-Phone/blob/3.0.2/src/Validation/Phone.php#L41).

https://github.com/Propaganistas/Laravel-Phone/blob/3.0.2/src/Validation/Phone.php#L105 is where things hit the fan, I would say. I'm not sure if `$inputField` is supposed to carry any other value than the potential name of the/a country field, but since `mobile` is both a validation parameter AND the name of the field under validation, `$inputField` ends up having the value `mobile`.
Given this, we will actually end up inside the if statement on https://github.com/Propaganistas/Laravel-Phone/blob/3.0.2/src/Validation/Phone.php#L110, and thus `'mobile'` gets appended to `$parameters` and the following `array_diff`s are not able to clean out `$leftovers` and we end up with an exception thrown on https://github.com/Propaganistas/Laravel-Phone/blob/3.0.2/src/Validation/Phone.php#L124.

@lyonlim: I'm suspecting `'phone'` is not the only key inside the assoc array you're validating? Might there be a `'mobile'` key in there aswell? That would explain your bug as per my description above. I cannot reproduce your behavior with just

```
        $validator = \Validator::make(
            ['phone' => '+46731234567'],
            ['phone' => 'phone:US,BE,mobile']
        );
        $validator->fails();
```

but this renders the same exception:

```
        $validator = \Validator::make(
            ['phone' => '+46731234567', 'mobile' => 'foo'],
            ['phone' => 'phone:US,BE,mobile']
        );
        $validator->fails();
```

**Comment by Propaganistas** [comment]
It seems the error you're both experiencing is caused by the ambiguity of the input field's name as it collides with a phone type. Since there's no real way of determining whether the parameter should be interpreted as an input field, phone type or even both I've implemented a minor change to throw a descriptive exception for these kind of situations. Please update to the latest version of the package.

To resolve the issue, simply rename the input field.

**Comment by joebon** [comment]
Sorry for a really late response.
Well, wether or not your suggestion "resolves" the issue I would say is up for debate.

Having a field named `mobile` (as in my case for instance) works perfectly fine in prior versions (2.8.5 for instance), but does not work anymore.
So requiring users of your repo to rename their fields to be able to update to the latest version is kind of a big deal, at least to me given the code base I'm using this package in.
Plus, the names we're talking about (`mobile`, `phone`?) are probably pretty common names a user would want to give fields using this repo.
I really don't mean to whine, just wanted to explain how this non-backward compatible change affects the usability of this package.
I'll see if I can come up with a solution which fixes this.

**Comment by Propaganistas** [comment]
Thanks for your insights @joebon . Please note however that you're comparing `2.8.5` against `3.0`. According to the semver specification a major version upgrade will most likely induce backward incompatible changes. While version 2 had some predefined considerations, version 3 is a complete rewrite and more generic, resulting in this very own ambiguity situation.

I invite you to make use of the supplied Rule object instead of relying on strings such as `mobile`, which is rather available for its ease of use.

```php
use Propaganistas\LaravelPhone\Rules\Phone as PhoneRule;

$rules = [
    'mobile' => with(new PhoneRule)->mobile()->country('SG', 'MY'),
];
```

**Comment by mikerockett** [comment]
I fell into this as well, and using `Rule` now presents a different exception:

> Invalid phone validation parameters: \”1\”.

Thrown from https://github.com/Propaganistas/Laravel-Phone/blob/a62652098a90e13cd978a5239e26bff947e31501/src/Validation/Phone.php#L129

With:

```php
'user.mobile' => ['required', Rule::phone()->mobile()->country('ZA')],
```

**Comment by mikerockett** [comment]
Upon further investigation, it looks like `mobile()` uses a constant of `1` from libphonenumber, which is why the ambiguity exception doesn’t get thrown.

So now, I need to ask why the suggestion to use the Rule helper was made – or perhaps it worked before and has since stopped working?

**Comment by Propaganistas** [comment]
Indeed, type juggle bug found & fixed. Thanks for insisting on this.

**Comment by Propaganistas** [comment]
New release `3.1.0` rolled out.

**Comment by mikerockett** [comment]
Thanks! Will test it out tomorrow afternoon (SAST)

**Comment by mikerockett** [comment]
Super sorry for the delay – all working this side, thanks!
